### ISSUE TITLE
[BUG] $ping command is still faulty. 

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#110]
> (node:4) UnhandledPromiseRejectionWarning: ReferenceError: client is not defined
> 2020-10-09T23:33:01.843042+00:00 app[worker.1]: at Object.execute (/app/src/commands/ping.js:11:45)
> 2020-10-09T23:33:01.843044+00:00 app[worker.1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
> 2020-10-09T23:33:01.843137+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> 2020-10-09T23:33:01.847679+00:00 app[worker.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> That was the issue with ping

That was the issue with ping in heroku's log

**Comment by kubeeek** [comment]
Can I take it?

**Comment by adhammo** [comment]
Can you assign it to me, please?

This exception was thrown because **client** is not defined in **ping.js** scope.

There are two solutions:
1. Give client to command args. (not that good)
2. Sperate client from **index.js** and give it its own module.

Update: I just noticed from discord.js docs that message class has a read-only client attribute. I'll go with this one.
