### ISSUE TITLE
[FEATURE] The embedded messages look kind of sloppy

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#128]
![image](https://user-images.githubusercontent.com/19593836/96367262-1cd23d80-1123-11eb-82a6-728f26d11e18.png)

That's the list command right now. Every notification on the bot shows a similar message. It would look really nice if we could get a message like the queue on groovy

![image](https://user-images.githubusercontent.com/19593836/96367272-383d4880-1123-11eb-9808-4d17bb939526.png)

Example:
1)     <list element>                        <author>
2)     <list element>                        <author>
.....
n)     <list element>                        <author>

**Comment by Remakh** [comment]
Could I do this?

**Comment by tomassirio** [comment]
Sure! I'll assign it to you. If you want to keep in contact, we have a [discord server](https://discord.gg/gbHhXS) were we discuss this and the other bots optimization

**Comment by Remakh** [comment]
Sure thanks very much!

**Comment by rgroves** [comment]
Hi @Remakh, how is the work on this issue going? Asking because another contributor wants to make some additions (See Issue #146) that will probably collide with what you're working on. If you're close to finishing, we may hold on that Issue until you can get a PR in. Otherwise, it will be a race to finish, and whoever gets in last will likely have to deal with managing merge conflicts or just reapplying their work over the latest code.

**Comment by Remakh** [comment]
Sorry I've had a lot of coursework and team projects recently, and still do if I'm being honest. If someone else would like to start and possibly finish it before me that's fine.

**Comment by rgroves** [comment]
Ok, thanks for the update.

**Comment by rgroves** [comment]
This was partially addressed by PR #148.
PR #149 should close this out once it's ready to be merged.

**Comment by rgroves** [comment]
I'm going to close this out since PR #149 was completed and merged. If further improvements to the bot messages are required, we can address them as a new issue.
