### ISSUE TITLE
[FEATURE] Refactor code to remove typos

### ISSUE THREAD

**Issue by RazCrimson** [tomassirio/ListBot#143]
**Is your feature request related to a problem? Please describe.**
There are a few typos in naming variables and syntax mistakes which are ignored implicitly. One example will be `embededMessage` which must be spelled as `embeddedMessage`. I guess this was copy/pasted, so its spelled in this manner in many modules.

**Describe the solution you'd like**
Would like those and syntax mistakes to be fixed.

**Describe alternatives you've considered**
I guess I can't consider alternatives for this. But yea, I have a PR.

**Comment by rgroves** [comment]
I think it would be better if spelling issues were handled separately from any syntax issues (meaning treated as two separate issues).

Can you explain what you mean by syntax errors? The bot wouldn't run if there were syntax errors.

**Comment by RazCrimson** [comment]
Well it missed out some awaits for promises related to sending messages(had like 5 of them). Errors might have been a wrong word to describe them.  

So, do I cancel the PR and make another issue for that? 

I will remove the await added for easterEggsCheck

**Comment by rgroves** [comment]
I think it makes sense to have one issue and PR that does the spelling corrections.

I haven't reviewed all of the code in the PR so I can't say for sure, but I would ask if you can elaborate on what issues are caused by the missing asyncs that you're adding in? Are you sure they are required? I would determine that and maybe speak to it in the Issue you open for it explicitly.

The reason to keep the PR for something like spelling and logic fixes separate is that if the logic changes need to be reverted for whatever reason, the spelling issues won't be reverted also, because they were in a separate PR. The goal should be to keep separate concerns isolated to individual Issues and PRs.

**Comment by rgroves** [comment]
Oh and to answer your question, yes. I would close the PR. It looks like the title of this issue (#143) has been updated to be the issue for the typos. So you should create a PR that address the typos/spelling issues only which will close that. Then open a separate issue and explain the problem you are seeing with the bot and how adding the async/await keywords fixes it.
