### ISSUE TITLE
[FEATURE] Standardizing Embed Formats

### ISSUE THREAD

**Issue by RazCrimson** [tomassirio/ListBot#146]
**Is your feature request related to a problem? Please describe.**
The Embed function in utils requires a `author` object to be passed as a parameter. But many locations in the code base pass `author.tag` into that. Some other locations send the `message.author.id` . Would like to standardize that to `message.author`.

**Describe the solution you'd like**
I would like a `Discord.User`/`message.author` instance of the message/command author to be passed as a parameter to the embed generator and access the tag attribute from that and also display the User's Avatar. 

**Additional context**
Current :
![image](https://user-images.githubusercontent.com/52282402/96953576-09eaaf00-150f-11eb-871f-2764dab14214.png)

Would like it to be:
![image](https://user-images.githubusercontent.com/52282402/96953618-20910600-150f-11eb-823e-0ee60bff0a1f.png)

**Comment by rgroves** [comment]
This looks like it would be a nice addition and make the message embeds look nicer. What do you think @tomassirio?

I believe Issue #128 which is in the same spirit as this and is already in the works. Let's check with the contributor there to see where there at, because if their close to finishing it would probably be better to apply work for this after their changes. Otherwise, y'all might step over each others work and have to deal with some messy merge conflicts.

**Comment by tomassirio** [comment]
They look really better and @RazCrimson is right about the redundancy in objects passed as parameters

**Comment by rgroves** [comment]
@RazCrimson It looks like Issue #128 isn't able to be worked on currently by the contributor who first requested it. Would you like to work on not only making the footer look better, but making the entire embed look a little better as described in #128? These are very much the same issue so you could tackle them both in a single PR and just mention in your PR comment that it closes them both. 

You can do your original suggestion only or both. It's up to you.

This would be a good time to get rid of `utils.generateListEmbed` It doesn't seem to be needed (it could just as easily use `utils.embedMessage` and falls in line with standardizing the embed messages.

Thanks!

**Comment by RazCrimson** [comment]
@rgroves Ok, will try doing it.

**Comment by RazCrimson** [comment]
@rgroves Should I add code blocks to embeds? Or should I directly just use code blocks? 

Using code blocks within a embed adds a limitation on the length of the list item. It goes beyond the length it wont look good.

**Comment by rgroves** [comment]
@RazCrimson Good job! I've reviewed the changes and for the most part they look good just a couple of adjustments are needed when you have a chance. 

My initial thoughts are as follow:

- Do you know what the length limitation is when using code blocks like that?
- I see you've chosen Nim as the formatter being used for the code block. If we go this route, maybe a future Issue and PR can address making this configurable (so that the chosen formatter can be pulled form the config object and set in the .env file.

The Nim formatting doesn't look great, but I imagine none of the code formatters will work perfectly for ListBot's purposes. 
![image](https://user-images.githubusercontent.com/891249/97086854-8226a280-15eb-11eb-96d6-30a9d05a0e02.png)

**Comment by RazCrimson** [comment]
@rgroves The description of a embed (where I insert code blocks text) has a length limit of 2048 characters. We might need to split it into multiple messages if it gets too long. 

As for making it into a format which can be specified in .env, its totally possible. Will make a new Issue for that after I am done with this, I guess.

We also need: 

- A PR to handle the messages which exceed the max length must be made.

- Format/pad the list with spaces to make it look better.

I also made some changes to standardize the usages of embeds. Take a look. There seems to be some redundant initialization of variables in the code base which need to be removed too.
