### ISSUE TITLE
Add a command for the Konami Code

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#73]
I was thinking that it could be added as an exception on the add command or add many. 

But it could be whatever you feel up to

**Comment by rgroves** [comment]
I'd like to pick this up, though I'm not clear on what is meant by "it could be added as an exception on the add command or add many." Can you clarify what should be implemented. Is a new command to be created or is this to be hooked into an existing command? 

And how is the Konami Code to be entered by the user? Would it be using emoji, like:
$⬆⬆⬇⬇⬅➡⬅➡BA
Or using a plain-text representation, like: 
$UUDDLRLRBA

Or should it be triggered by the add command, like:
$add ⬆⬆⬇⬇⬅➡⬅➡BA

And what would you like the code itself to trigger? Is this just meant to be an easter egg to do something interesting/funny?

**Comment by tomassiriouala** [comment]
I really like this option 

> $add ⬆⬆⬇⬇⬅➡⬅➡BA

It should be an Easter Egg on the add function. I think that it should ommit the DB insertion and just return an embedded message with an Egg or something Konami Related (It could also be a Kojima being fired joke).

I'll assign it to you @rgroves. Meanwhile, join us at the [discord channel ](http://www.discord.io/listbot) in which we are discussing ListBot related stuff

**Comment by rgroves** [comment]
@tomassirio I implemented this so that it just returns a random message from a set I came up with on the fly. These random messages can be improved or added to in the future.

The messages look like this:
![image](https://user-images.githubusercontent.com/891249/96077670-0c496b00-0e76-11eb-8888-35e74c7f9a75.png)

**Comment by rgroves** [comment]
Also, it looks like the code base is in a somewhat broken state. I had to modify `src\commands\polls.js` to remove an error and modify the `devMongoUrl` connection string in `src\config\index.js`. (Note: I was not using Docker)

It also looks like linting checks may have been modified or added, because it looks like files that weren't part of my PR changes are failing checks. Let me know how to proceed or if this is fine. Thanks!

**Comment by tomassirio** [comment]
We've had a lot of contributions in the past days and I couldn't merge everything appropriately. One of the Contributors is working on a test suit case to solve most of this issues. But if you are willing to give a hand, I can open an issue for you to fix those things
